language: php

php: '7.2'

before-install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in deploy.pem.enc -out .travis/deploy.pem -d
  - composer self-update

install: composer install

script: phpunit

after-success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.pem
- ssh-add .travis/deploy.pem
- git remote add deploy ssh://$USER@$HOST:$DIRECTORY
- git push deploy