# https://oncletom.io/2016/travis-ssh-deploy/
dist: xenial
addons:
  ssh_known_hosts: quentinburgniard.com
language: php
php: '7.2'
git:
  depth: 1
before_install:

# https://docs.travis-ci.com/user/encrypting-files/
# https://hub.docker.com/r/skandyla/travis-cli/
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in .travis/deploy.pem.enc -out .travis/deploy.pem -d

install: composer install
script: true
# https://docs.travis-ci.com/user/deployment/script/
deploy:
  provider: script
  script: bash .travis/deploy.sh

  # https://docs.travis-ci.com/user/deployment/#uploading-files-and-skip_cleanup
  skip_cleanup: true

# https://docs.travis-ci.com/user/notifications/#configuring-email-notifications
notifications:
  email:
    on_success: never
    on_failure: always
