dist: xenial
addons:
  ssh_known_hosts: quentinburgniard.com
language: php
php: '7.2'
git:
  depth: 1
before_install:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in .travis/deploy.pem.enc -out .travis/deploy.pem -d
install: composer install
script: true
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
notifications:
  email:
    on_success: never
    on_failure: always
